import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  KeyboardAvoidingView,
} from "react-native";

const Form = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleEmailChange = (text) => {
    setEmail(text);
  };

  const handlePasswordChange = (text) => {
    setPassword(text);
  };

  const handleSubmit = () => {
    console.log(email, password);
  };

  return (
    <KeyboardAvoidingView behavior="position" style={styles.container}>
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />
      <Text>Email</Text>
      <TextInput
        value={email}
        onChangeText={handleEmailChange}
        keyboardType="email-address"
      />
      <Text>Email</Text>
      <TextInput
        value={password}
        onChangeText={handlePasswordChange}
        secureTextEntry={true}
      />

      <TouchableOpacity
        onPress={handleSubmit}
        style={{ padding: 16, backgroundColor: "tomato" }}
      >
        <Text>Submit</Text>
      </TouchableOpacity>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default Form;
